apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.image-pull-policy: IfNotPresent
    kompose.service.type: nodeport
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.image-pull-policy: IfNotPresent
        kompose.service.type: nodeport
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: MONGO_CONNECTION_STRING
              value: mongodb://db:27017
          image: api
          imagePullPolicy: IfNotPresent
          name: api
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
